# ETL

In [31]:
import pandas as pd
import os
from georef import add_unidades_territoriales_to_df

In [32]:
#file
df_alumnos = pd.read_csv('data/input/alumnos.csv',delimiter=',')
df_carreras = pd.read_csv('data/input/carreras.csv',delimiter=',')
df_universidades = pd.read_csv('data/input/universidades.csv',delimiter=',')

In [33]:
df_carreras.head(10)

                                             carrera carrera_grupo
0                                            Abogado       Abogado
1      Abogado - Ciclo de Complementacion Curricular       Abogado
2                                       Abogado - MD       Abogado
3  Abogado Especialista en Administracion de Just...       Abogado
4  Abogado especialista en Asesoramiento de Empresas       Abogado
5  Abogado Especialista en Asesoria Juridica de E...       Abogado
6  Abogado especialista en Derecho Administrativo...       Abogado
7  Abogado Especialista en Derecho Administrativo...       Abogado
8          Abogado especialista en Derecho Ambiental       Abogado
9  Abogado especialista en Derecho de Alta Tecnol...       Abogado

In [34]:
df_alumnos.head(10)

,anio,institucion_tipo,institucion_provincia,interior_caba,institucion_nombre,institucion_nombre_new,unidad_academica,unidad_academica_new,carrera_nombre,carrera_titulo,...,egresados_varones,egresados_mujeres,tasa_de_inscripcion_total,tasa_de_graduacion_total,tasa_de_inscripcion_varon,tasa_de_graduacion_varon,tasa_de_inscripcion_mujer,tasa_de_graduacion_mujer,tasa_de_inscripcion_mujer_hombre,tasa_de_graduacion_mujer_hombre
0,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Licenciado en Composicion,...,11.0,NaN,0.277778,0.076389,0.675000,1.000000,0.325000,0.000000,0.481481,0.000000
1,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Licenciado en Direccion Coral,...,1.0,1.0,0.000000,0.666667,0.000000,0.500000,0.000000,0.500000,0.000000,1.000000
2,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Licenciado en Direccion Orquestal,...,10.0,5.0,0.188679,0.283019,0.800000,0.666667,0.200000,0.333333,0.250000,0.500000
3,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Tecnico Universitario en Lenguaje Musical Basico,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Tecnico Universitario en Produccion Musical Ap...,...,NaN,NaN,0.277778,0.000000,0.700000,0.000000,0.300000,0.000000,0.428571,0.000000
5,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Ciencias Agrarias,Facultad de Ciencias Agrarias,Administracion de Empresas Agropecuarias,Magister en Gestion de la Empresa Agroalimentaria,...,6.0,1.0,0.000000,0.166667,0.000000,0.857143,0.000000,0.142857,0.000000,0.166667
6,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Ciencias Agrarias,Facultad de Ciencias Agrarias,Produccion e Ingenieria Agropecuaria,Ingeniero en Produccion Agropecuaria,...,13.0,8.0,0.260000,0.060000,0.725275,0.619048,0.274725,0.380952,0.378788,0.615385
7,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Ciencias Agrarias,Facultad de Ciencias Agrarias,Produccion e Ingenieria Agropecuaria,Tecnico en Produccion Agropecuaria,...,NaN,2.0,0.220126,0.012579,0.771429,0.000000,0.228571,1.000000,0.296296,0.000000
8,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Ciencias Agrarias,Facultad de Ciencias Agrarias,Tecnologia e Ingenieria en Alimentos,Ingeniero en Alimentos,...,9.0,18.0,0.209459,0.182432,0.225806,0.333333,0.774194,0.666667,3.428571,2.000000
9,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Ciencias Agrarias,Facultad de Ciencias Agrarias,Tecnologia e Ingenieria en Alimentos,Licenciado en Tecnologia de los Alimentos,...,1.0,7.0,0.000000,0.000000,0.000000,0.125000,0.000000,0.875000,0.000000,7.000000

In [35]:
df_universidades.head(10)

,institucion_nombre,institucion_direccion,api,coordenadas
0,Universidad CAECE,Av. de Mayo 866,http://apis.datos.gob.ar/georef/api/direccione...,"-34.608865810462795,-58.378716306442456"
1,Universidad Nacional de Córdoba,Av. Haya de la Torre s/n,http://apis.datos.gob.ar/georef/api/direccione...,"-31.4354809,-64.1877589"
2,Universidad Nacional de Rosario,Maipú 1065,http://apis.datos.gob.ar/georef/api/direccione...,"-32.950309649805945,-60.636126952347716"
3,Universidad Nacional de Río Cuarto,Ruta Nac. 36 - Km. 601,http://apis.datos.gob.ar/georef/api/direccione...,"-33.084594014186514,-64.3349444221352"
4,Universidad Nacional de San Juan,Mitre 396,http://apis.datos.gob.ar/georef/api/direccione...,"-31.5354691,-68.5412352,15"
5,Universidad Nacional de San Luis,Ejército de los Andes 950,http://apis.datos.gob.ar/georef/api/direccione...,"-33.2962223,-66.3441194"
6,Universidad Nacional del Comahue,Av. Santa Fe 1845,http://apis.datos.gob.ar/georef/api/direccione...,"-34.59583822943477,-58.393932130303796"
7,Universidad Nacional del Sur,Av. Alem 1253,http://apis.datos.gob.ar/georef/api/direccione...,"-38.67866305629395,-62.29611089500422"
8,Universidad de Buenos Aires,Viamonte 430,http://apis.datos.gob.ar/georef/api/direccione...,"-34.59971093266858,-58.37308898582941"
9,Universidad Católica de Salta,Av. Presidente Roque Sáenz Peña 950,http://apis.datos.gob.ar/georef/api/direccione...,"-24.7399552,-65.3940334"

## Calculo evolucion de genero en carreras

In [36]:
df_alumnos_merged = df_alumnos.merge(df_carreras, how="left", left_on="carrera_titulo", right_on="carrera")

In [37]:
col_nulls = df_alumnos_merged.isnull().any()
col_nulls

anio                                False
institucion_tipo                    False
institucion_provincia                True
interior_caba                        True
institucion_nombre                  False
institucion_nombre_new              False
unidad_academica                    False
unidad_academica_new                False
carrera_nombre                      False
carrera_titulo                      False
institucion_gestion                 False
carrera_titulo_nivel                False
area_de_estudio                     False
estudiantes_total                    True
estudiantes_varones                  True
estudiantes_mujeres                  True
nuevos_inscriptos_total              True
nuevos_inscriptos_varones            True
nuevos_inscriptos_mujeres            True
reinscriptos_total                   True
reinscriptos_varones                 True
reinscriptos_mujeres                 True
egresados_total                      True
egresados_varones                    True
egresados_mujeres                    True
tasa_de_inscripcion_total           False
tasa_de_graduacion_total            False
tasa_de_inscripcion_varon           False
tasa_de_graduacion_varon            False
tasa_de_inscripcion_mujer           False
tasa_de_graduacion_mujer            False
tasa_de_inscripcion_mujer_hombre    False
tasa_de_graduacion_mujer_hombre     False
carrera                             False
carrera_grupo                        True
dtype: bool

In [38]:
df_alumnos_merged.carrera_grupo.isnull().value_counts()

False    55911
True      2929
Name: carrera_grupo, dtype: int64

In [39]:
variables = [
    "estudiantes_total","estudiantes_varones","estudiantes_mujeres",
    "nuevos_inscriptos_total","nuevos_inscriptos_varones","nuevos_inscriptos_mujeres",
    "egresados_total","egresados_varones","egresados_mujeres",
]

In [40]:
df_evolucion_carrera = df_alumnos_merged.groupby(["anio","carrera_grupo"]).sum()

In [41]:
df_evolucion_carrera = df_evolucion_carrera[variables]
df_evolucion_carrera = df_evolucion_carrera.reset_index()
#df_evolucion_carrera = df_evolucion_carrera.drop("index",1)

In [42]:
df_evolucion_carrera.head(10)

,anio,carrera_grupo,estudiantes_total,estudiantes_varones,estudiantes_mujeres,nuevos_inscriptos_total,nuevos_inscriptos_varones,nuevos_inscriptos_mujeres,egresados_total,egresados_varones,egresados_mujeres
0,2010,Abogado,212710.0,76898.0,100320.0,46024.0,18303.0,22110.0,12485.0,3743.0,4973.0
1,2010,Arquitectura,58030.0,21749.0,20843.0,10118.0,3686.0,3828.0,2662.0,916.0,1094.0
2,2010,Arte,83766.0,23655.0,33544.0,22501.0,7071.0,9505.0,2990.0,842.0,1326.0
3,2010,Deporte,2727.0,1569.0,1158.0,855.0,526.0,329.0,154.0,68.0,86.0
4,2010,Derecho,23486.0,9862.0,12995.0,9088.0,4219.0,4598.0,3302.0,1364.0,1873.0
5,2010,Economicas,403917.0,159459.0,184617.0,95739.0,42092.0,43736.0,25867.0,10359.0,11976.0
6,2010,Educacion,117673.0,26602.0,85552.0,35922.0,8996.0,25606.0,8068.0,1648.0,5919.0
7,2010,Exactas,51105.0,20392.0,24877.0,12816.0,5299.0,6285.0,2721.0,1089.0,1436.0
8,2010,Ingenieria,100864.0,78529.0,13448.0,20778.0,15590.0,3088.0,4204.0,3192.0,595.0
9,2010,Letras,2759.0,216.0,937.0,497.0,53.0,180.0,168.0,22.0,112.0

In [43]:
df_evolucion_carrera["estudiantes_mujeres_pct"] = df_evolucion_carrera.estudiantes_mujeres/df_evolucion_carrera.estudiantes_total
#incriptas como predictor de composicion e interes.
df_evolucion_carrera["inscripciones_mujeres_pct"] = df_evolucion_carrera.nuevos_inscriptos_mujeres/df_evolucion_carrera.nuevos_inscriptos_total

In [44]:
df_evolucion_carrera.to_csv("data/output/carreras_evolucion_genero.csv", encoding = "UTF8", index = False)

## Grafico exploratorio

### carreras

In [45]:
df_evolucion_carrera_carreras = df_alumnos_merged.groupby(["anio","carrera_grupo","carrera_nombre"]).sum()

In [46]:
df_evolucion_carrera_carreras = df_evolucion_carrera_carreras[variables]
df_evolucion_carrera_carreras = df_evolucion_carrera_carreras.reset_index()

In [47]:
df_evolucion_carrera_carreras["estudiantes_mujeres_pct"] = df_evolucion_carrera_carreras.estudiantes_mujeres/df_evolucion_carrera_carreras.estudiantes_total
#incriptas como predictor de composicion e interes.
df_evolucion_carrera_carreras["inscripciones_mujeres_pct"] = df_evolucion_carrera_carreras.nuevos_inscriptos_mujeres/df_evolucion_carrera_carreras.nuevos_inscriptos_total

In [48]:
df_evolucion_carrera_carreras.to_csv("data/output/grupo_carreras_evolucion_genero.csv", encoding = "UTF8", index = False)

In [49]:
df_evolucion_carrera_universidad = df_alumnos_merged.groupby(["anio","carrera_grupo","institucion_nombre_new"]).sum()

In [50]:
df_evolucion_carrera_universidad = df_evolucion_carrera[variables]
df_evolucion_carrera_universidad = df_evolucion_carrera.reset_index()

In [51]:
df_evolucion_carrera_universidad["estudiantes_mujeres_pct"] = df_evolucion_carrera_universidad.estudiantes_mujeres/df_evolucion_carrera_universidad.estudiantes_total
#incriptas como predictor de composicion e interes.
df_evolucion_carrera_universidad["inscripciones_mujeres_pct"] = df_evolucion_carrera_universidad.nuevos_inscriptos_mujeres/df_evolucion_carrera_universidad.nuevos_inscriptos_total
#agregar ratio de hombres

In [52]:
df_evolucion_carrera_universidad.to_csv("data/output/carreras_universidad_evolucion_genero.csv", encoding = "UTF8", index = False)

# ETL Geo referenciado

In [53]:
df_universidades["lat"] = df_universidades['coordenadas'].str.split(",").str[0]
df_universidades["lon"] = df_universidades['coordenadas'].str.split(",").str[1]

In [54]:
#df_universidades = add_unidades_territoriales_to_df(df_universidades, lat_col="lat", lon_col="lon")

In [55]:
df_universidades.head()

,institucion_nombre,institucion_direccion,api,coordenadas,lat,lon
0,Universidad CAECE,Av. de Mayo 866,http://apis.datos.gob.ar/georef/api/direccione...,"-34.608865810462795,-58.378716306442456",-34.608865810462795,-58.378716306442456
1,Universidad Nacional de Córdoba,Av. Haya de la Torre s/n,http://apis.datos.gob.ar/georef/api/direccione...,"-31.4354809,-64.1877589",-31.4354809,-64.1877589
2,Universidad Nacional de Rosario,Maipú 1065,http://apis.datos.gob.ar/georef/api/direccione...,"-32.950309649805945,-60.636126952347716",-32.950309649805945,-60.636126952347716
3,Universidad Nacional de Río Cuarto,Ruta Nac. 36 - Km. 601,http://apis.datos.gob.ar/georef/api/direccione...,"-33.084594014186514,-64.3349444221352",-33.084594014186514,-64.3349444221352
4,Universidad Nacional de San Juan,Mitre 396,http://apis.datos.gob.ar/georef/api/direccione...,"-31.5354691,-68.5412352,15",-31.5354691,-68.5412352

In [56]:
df_universidades_merged = df_alumnos_merged.merge(df_universidades, how="left", left_on="institucion_nombre", right_on="institucion_nombre")
df_universidades_merged.head()

,anio,institucion_tipo,institucion_provincia,interior_caba,institucion_nombre,institucion_nombre_new,unidad_academica,unidad_academica_new,carrera_nombre,carrera_titulo,...,tasa_de_graduacion_mujer,tasa_de_inscripcion_mujer_hombre,tasa_de_graduacion_mujer_hombre,carrera,carrera_grupo,institucion_direccion,api,coordenadas,lat,lon
0,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Licenciado en Composicion,...,0.000000,0.481481,0.0,Licenciado en Composicion,Arte,NaN,NaN,NaN,NaN,NaN
1,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Licenciado en Direccion Coral,...,0.500000,0.000000,1.0,Licenciado en Direccion Coral,Arte,NaN,NaN,NaN,NaN,NaN
2,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Licenciado en Direccion Orquestal,...,0.333333,0.250000,0.5,Licenciado en Direccion Orquestal,Arte,NaN,NaN,NaN,NaN,NaN
3,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Tecnico Universitario en Lenguaje Musical Basico,...,0.000000,0.000000,0.0,Tecnico Universitario en Lenguaje Musical Basico,Salud,NaN,NaN,NaN,NaN,NaN
4,2010,Universidad,Ciudad Autonoma de Buenos Aires,CABA,Pontificia Universidad Catolica Argentina Sant...,Pontificia Universidad Catolica Argentina Sant...,Facultad de Artes y Ciencias Musicales,Facultad de Artes y Ciencias Musicales,Musica,Tecnico Universitario en Produccion Musical Ap...,...,0.000000,0.428571,0.0,Tecnico Universitario en Produccion Musical Ap...,Arte,NaN,NaN,NaN,NaN,NaN

In [57]:
df_evolucion_universidades = df_universidades_merged.groupby(["anio","provincia_id","carrera_grupo"]).sum()
df_evolucion_universidades = df_evolucion_universidades[variables]
df_evolucion_universidades = df_evolucion_universidades.reset_index()
df_evolucion_universidades.head()

KeyError: 'provincia_id'

In [ ]:
df_evolucion_universidades["estudiantes_mujeres_pct"] = df_evolucion_universidades.estudiantes_mujeres/df_evolucion_universidades.estudiantes_total

In [ ]:
estudiantes_totales = df_evolucion_universidades.groupby(["anio", 'provincia_id']).sum()["estudiantes_total"]

In [ ]:
df_evolucion_universidades['estudiantes_grupo_pct'] = df_evolucion_universidades.apply(
    lambda row: row["estudiantes_total"] / estudiantes_totales[row["anio"], row["provincia_id"]],
    axis=1
)

In [ ]:
df_evolucion_universidades.head()

In [ ]:
df_evolucion_universidades.to_csv("data/output/ubicacion_evolucion_genero.csv", encoding = "UTF8", index = False)

In [ ]:
##ETL Markers de universidades

In [ ]:
def crear_universidad(mapa,latitud, longitud, universidad_nombre, carreras_grupos):
    """ Pone una universidad en el mapa con información en el marker.

    Args:
        latitud (float):
        longitud (float):
        universidad_nombre (str):
        carreras_grupos (list):
    """

In [ ]:
def concatenate_map(grupos_carreras):
    grupos_str = [str(grupo) for grupo in set(grupos_carreras) if pd.notnull(grupo)]
    return ",".join(grupos_str)

In [ ]:
serie_lista_grupos = df_universidades_merged.groupby("institucion_nombre_new")["carrera_grupo"].apply(concatenate_map)
serie_lista_carrera = df_universidades_merged.groupby("institucion_nombre_new")["carrera_nombre"].apply(concatenate_map)

In [ ]:
df_ubicacion_universidades_grupos = df_universidades.merge(
    serie_lista_grupos, how="left", left_on="institucion_nombre", right_index=True)
df_ubicacion_universidades_grupos = df_ubicacion_universidades_grupos.merge(
    serie_lista_carrera, how="left", left_on="institucion_nombre", right_index=True)

In [ ]:
df_ubicacion_universidades_grupos.to_csv("data/output/universidades.csv", encoding = "UTF8", index = False)
#tasas de egresos pero no lineamente, buscar la formula, estandariza el año de duracion.